name: CI

on: [push]

jobs:
  build:

    runs-on: Ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - name: Install packages / configure
      run: |
        sudo apt-get install libsystemd-dev
        sudo timedatectl set-timezone 'Australia/Melbourne'

    - name: make
      run: make all

    - name: test
      env:
        JERS_TEST_DEBUG: "Y"
      run: make test

